baseURL = "https://longhnguyen.net/"
languageCode = "en-us"
pagination.pagerSize = 6
theme = "portio"
title = "Long Nguyen | Portfolio"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 6
[[menu.main]]
name = "Contact"
url = "contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "Homepage"
url = "https://longhnguyen.net/"
weight = 1
[[menu.sitemap]]
name = "Resume/CV"
url = "Resume.pdf"
weight = 2
[[menu.sitemap]]
name = "Contact"
url = "contact"
weight = 4


[params]
blogPageURL = "writing"
contactLink = "contact"
copyright = "All Rights Reserved. Copyright © Long Nguyen 2024"
footerLogo = "images/contact/footer-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/2ORFL1T"
googleAnalytics = "G-GRLVE97S23"
logo = "images/site-navigation/logo.png"
custom_css = ["css/custom.css"]

[params.address]
address = "Bloomington, Indiana, United States"
email = "longnguyen.hhoang@gmail.com" 
openingHours = "Available anytime."


[params.map]
APIkey = "AIzaSyD2WardCPFCJsUgTeWNlMDEWJe5lL-YCfM"
latitude = "39.165325"
longitude = "-86.526386"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-github-alt"
url = "https://github.com/longcherry1102"
weight = 1
[[params.social]]
icon = "fa-linkedin"
url = "https://www.linkedin.com/in/long-nguyen-/"
weight = 2
[[params.social]]
icon = "fa-envelope"
url = "mailto:longnguyen.hhoang@gmail.com"
weight = 6
